#!/bin/bash

set -e

case "$1" in
	configure)

	# source linuxmuster-base-config
	. /usr/share/linuxmuster/config/dist.conf || exit 1
	. $HELPERFUNCTIONS || exit 1
	
	# basedir holding configuration files for
	# linuxmuster-nagios
	LINUXMUSTERNAGIOSBASE=/var/lib/linuxmuster-nagios

	# Nagiosconfigfiles
	NAGIOSCONF=/etc/nagios3

	# remove distributed config
	rm -f /etc/nagios3/conf.d/*nagios2.cfg

	# overwrite configuration with 
	# linuxmuster-nagios-default 
	# configuration
	cp -ar $LINUXMUSTERNAGIOSBASE/config/nagios3 /etc/

	# provide custom configuration file when necessary
	if [ ! -f /etc/nagios3/conf.d/linuxmuster_custom.cfg ]; then
	 cp -a $LINUXMUSTERNAGIOSBASE/custom_config/nagios* /etc/
	fi
	
	# provide commands.cfg & resource.cfg if missing
	for i in commands resource; do
	conf="/etc/nagios3/$i.cfg"
	 if [ ! -e "$i" ]; then
	  touch "$i"
      chmod 640 "$i"
      chgrp nagios "$i"
	 fi
	done

	# remove defect nagios2 link in /etc/apache2/conf.d
	rm -f /etc/apache2/conf.d/nagios2*

	# remove obsolete nagios entries from sudoers file
	if grep -q "LML-NAGIOS" /etc/sudoers; then
	 echo "Removing obsolete nagios stuff from /etc/sudoers."
	 cp /etc/sudoers /etc/sudoers.dpkg-bak
	 sed '/# LML-NAGIOS-START/,/# LML-NAGIOS-END/ d' -i /etc/sudoers
	 visudo -c
	fi
	
	# secure permissions for /etc/sudoers.d/nagios
	chmod 440 /etc/sudoers.d/nagios
	visudo -c -f /etc/sudoers.d/nagios

	# Modifying permissions in /var/lib/nagios (debian bug in nagios 2.5)
	chmod 755 /var/lib/nagios3
	chmod 775 /var/lib/nagios3/rw
	chown nagios.www-data /var/lib/nagios3/rw
	chmod g+s /var/lib/nagios3/rw

	# fixing permissions for logs
	chmod 755 /var/log/nagios3
	chown nagios.root /var/log/nagios3
	chmod u+s /var/log/nagios3

	# Fixing perm for /etc/nagios3/conf.d - nagios has to own this dir for
	# nagios-grapher to work
	chown nagios /etc/nagios3/conf.d

	# removing nagios2 config if existent
	if [ -d /etc/nagios2 ]; then
	 # backup nagios2 cfg
	 tar -cvzf /etc/nagios3/nagios2.conf.backup.tgz /etc/nagios2/
	 # remove nagios2 config
	 for i in /etc/nagios2 /etc/init.d/nagios2 \
	          /var/lib/linuxmuster-nagios/config/nagios2 \
	          /etc/rc*.d/*nagios2 /etc/default/nagios2 \
	          /etc/logrotate.d/nagios2-common /var/lib/nagios2; do
	  [ -e "$i" ] && rm -rf "$i"
	 done
	fi

	# tschmitt: do this only if linuxmuster.net is configured
	if [ -e "$INSTALLED" ]; then

	 # Fixing auth configuration in /etc/nagios3/apache2.conf
	 sed -e "s/###basedn###/$basedn/" $LINUXMUSTERNAGIOSBASE/templates/apache2.conf.tpl > /etc/nagios3/apache2.conf

	 # configure nagios
	 /usr/sbin/linuxmuster-nagios-setup

	 # restarting nagios
	 /etc/init.d/nagios3 stop
	 /etc/init.d/nagios3 start

	 # restarting apache2 webserver
	 /etc/init.d/apache2 reload

	fi

	;;

    abort-upgrade|abort-remove|abort-deconfigure)

	;;

    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
	;;

esac

exit 0
