#!/bin/bash
#
# thomas@linuxmuster.net
# 04.04.2013
# GPL v3
#

set -e

case "$1" in

	configure)

	# source linuxmuster-base-config
	. /usr/share/linuxmuster/config/dist.conf || exit 1
	. $HELPERFUNCTIONS || exit 1
	
	# basedir holding configuration files for
	# linuxmuster-nagios
	NAGIOSTPLBASEDIR=/var/lib/linuxmuster-nagios

	# Nagiosconfigfiles
	NAGIOSCONFDIR=/etc/nagios3
	APACHENAGIOSCONF="$NAGIOSCONFDIR/apache2.conf"
	LINUXMUSTERNAGIOSCONF="$SYSCONFDIR/nagios.conf"

	# remove distributed config
	rm -f $NAGIOSCONFDIR/conf.d/*nagios2.cfg

	# overwrite configuration with linuxmuster-nagios default configuration
	cp -ar $NAGIOSTPLBASEDIR/config/nagios3 /etc/

	# provide custom configuration file if necessary
	if [ ! -f "$NAGIOSCONFDIR/conf.d/linuxmuster_custom.cfg" ]; then
	 cp -a $NAGIOSTPLBASEDIR/custom_config/nagios* /etc/
	fi

	# remove defect nagios2 link in /etc/apache2/conf.d
	rm -f /etc/apache2/conf.d/nagios2*

	# remove obsolete nagios entries from sudoers file
	if grep -q "LML-NAGIOS" /etc/sudoers; then
	 echo "Removing obsolete nagios stuff from /etc/sudoers."
	 cp /etc/sudoers /etc/sudoers.dpkg-bak
	 sed '/# LML-NAGIOS-START/,/# LML-NAGIOS-END/ d' -i /etc/sudoers
	 visudo -c
	fi

	# secure permissions for sudoers
	chown root:root /etc/sudoers* -R
	chmod 755 /etc/sudoers.d
	chmod 440 /etc/sudoers
	chmod 440 /etc/sudoers.d/*
	visudo -c -f /etc/sudoers.d/nagios

	# Modifying permissions in /var/lib/nagios (debian bug in nagios 2.5)
	chmod 755 /var/lib/nagios3
	chmod 775 /var/lib/nagios3/rw
	chown nagios.www-data /var/lib/nagios3/rw
	chmod g+s /var/lib/nagios3/rw

	# fixing permissions for logs
	chmod 755 /var/log/nagios3
	chown nagios.root /var/log/nagios3
	chmod u+s /var/log/nagios3

	# Fixing perm for /etc/nagios3/conf.d - nagios has to own this dir for
	# nagios-grapher to work
	chown nagios $NAGIOSCONFDIR/conf.d

	# removing nagios2 config if existent
	if [ -d /etc/nagios2 ]; then
	 # backup nagios2 cfg
	 tar -cvzf $NAGIOSCONFDIR/nagios2.conf.backup.tgz /etc/nagios2/
	 # remove nagios2 config
	 for i in /etc/nagios2 /etc/init.d/nagios2 \
	          /var/lib/linuxmuster-nagios/config/nagios2 \
	          /etc/rc*.d/*nagios2 /etc/default/nagios2 \
	          /etc/logrotate.d/nagios2-common /var/lib/nagios2; do
	  [ -e "$i" ] && rm -rf "$i"
	 done
	fi
 
	# nagios: remove obsolete paedml stuff
	if grep -q -i paedml "$LINUXMUSTERNAGIOSCONF" || grep -q SSHIPCOP "$LINUXMUSTERNAGIOSCONF"; then
	 echo "Fixing $LINUXMUSTERNAGIOSCONF."
	 cp "$LINUXMUSTERNAGIOSCONF" "$LINUXMUSTERNAGIOSCONF.dpkg-bak"
	 sed -e 's|^DESC_SERVER=.*|DESC_SERVER="linuxmuster.net Server"|
	         s|^DESC_FW=.*|DESC_FW="linuxmuster.net Firewall"|
	         s|^DESC_SERVERGROUP=.*|DESC_SERVERGROUP="linuxmuster.net Server"|
	         s|^SSHIPCOP_PORT|SSHFIREWALL_PORT|' -i "$LINUXMUSTERNAGIOSCONF"
	fi

	# Fixing auth configuration and DirectoryIndex (#114) in /etc/nagios3/apache2.conf
	searchstr="AuthLDAPURL ldap://127.0.0.1/$basedn?uid"
	if ! grep -q "$searchstr" "$APACHENAGIOSCONF" || ! grep -q index.php "$APACHENAGIOSCONF"; then
	 echo "Fixing $APACHENAGIOSCONF."
	 tpl="$NAGIOSTPLBASEDIR/templates/apache2.conf.tpl"
	 cp "$APACHENAGIOSCONF" "$APACHENAGIOSCONF.dpkg-bak"
	 sed -e "s/###basedn###/$basedn/" "$tpl" > "$APACHENAGIOSCONF"
	fi

	# tschmitt: do this only if linuxmuster.net is configured
	if [ -e "$INSTALLED" ]; then

	 # configure nagios
	 /usr/sbin/linuxmuster-nagios-setup

	 # restarting nagios
	 /etc/init.d/nagios3 stop
	 /etc/init.d/nagios3 start

	 # restarting apache2 webserver
	 /etc/init.d/apache2 reload

	fi

	;;

    abort-upgrade|abort-remove|abort-deconfigure)

	;;

    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
	;;

esac

exit 0
