#!/bin/sh

SSH_COMMAND="ssh -p 222 ipcop"
SCP_COMMAND="scp -P 222"
LIB_DIR=/root/
IPCOP_FILES_ARCHIVE=linuxmuster-nagios-ipcop-files.tgz
IPCOP_CONFIG_FILE=ipcop_nagios.conf
IPCOP_INIT_SCRIPT=/usr/local/nagios/scripts/linuxmuster-init
NAGIOS_LOCAL_HOME=/etc/nagios3/
NAGIOSCONFIG=/etc/linuxmuster/nagios.conf

#delete default stuff on ipcop
$SSH_COMMAND rm -rf /usr/local/nagios/scripts 
$SSH_COMMAND rm -rf /usr/local/nagios/plugins
$SSH_COMMAND rm -rf /usr/local/nagios/.ssh

# copy archive to ipcop
$SCP_COMMAND $LIB_DIR/$IPCOP_FILES_ARCHIVE ipcop:/

# extract files on ipcop
$SSH_COMMAND tar -C / -xzf /$IPCOP_FILES_ARCHIVE 

# delete archive file
$SSH_COMMAND rm /$IPCOP_FILES_ARCHIVE

# initialize settings on ipcop
$SSH_COMMAND $IPCOP_INIT_SCRIPT

# ssh setup
if [ -f $NAGIOS_LOCAL_HOME/.ssh/id_dsa ]; then
  echo "Key exists, copying key to IPCOP"
  $SCP_COMMAND $NAGIOS_LOCAL_HOME/.ssh/id_dsa.pub ipcop:/usr/local/nagios/.ssh/authorized_keys
else
  echo "No SSH-Key for nagios found, creating one..."
  mkdir -p $NAGIOS_LOCAL_HOME/.ssh
  cd $NAGIOS_LOCAL_HOME/.ssh
  ssh-keygen -b 1024 -f id_dsa -t dsa -N '' 
fi

# check updated nagios.conf 
UPDATED=""
UPDATED=`grep IPCOPSQUIDGUARDPROC $NAGIOSCONFIG`
if [ -z "$UPDATED" ]; then 
   echo "Modifying nagios configuration file..."
   cat $LIB_DIR/$IPCOP_CONFIG_FILE >> $NAGIOSCONFIG
fi
